"""
Hard-coded government scheme rules for 25 schemes.
Each scheme dict matches the SQLite 'schemes' table schema.
"""

import json

SCHEMES = [
   
    {
        "id": "pm-kisan",
        "name_en": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "name_hi": "प्रधानमंत्री किसान सम्मान निधि",
        "name_bn": "প্রধানমন্ত্রী কিষাণ সম্মান নিধি",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "cash",
        "benefit_summary": "₹6,000/year in 3 installments directly to farmer's bank account",
        "benefit_amount": 6000.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 200000.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Land Records / Khatian", "Bank Passbook"]),
        "apply_url": "https://pmkisan.gov.in",
        "helpline": "155261",
        "processing_days": 30,
        "deadline": "Open",
        "rejection_tips": "Ensure land is in your name. Joint ownership is also eligible. Avoid duplicate registrations.",
    },
    {
        "id": "ayushman-bharat",
        "name_en": "Ayushman Bharat PMJAY",
        "name_hi": "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना",
        "name_bn": "আয়ুষ্মান ভারত পিএমজেএওয়াই",
        "ministry": "Ministry of Health and Family Welfare",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "insurance",
        "benefit_summary": "₹5 lakh/year health insurance for secondary & tertiary hospitalisation",
        "benefit_amount": 500000.0,
        "min_age": 0,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "student", "unemployed", "street-vendor", "artisan", "woman-homemaker", "salaried", "self-employed"]),
        "bpl_required": 1,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Ration Card (BPL)"]),
        "apply_url": "https://pmjay.gov.in",
        "helpline": "14555",
        "processing_days": 7,
        "deadline": "Open",
        "rejection_tips": "Check if your family is in SECC 2011 database. BPL ration card is the easiest proof.",
    },
    {
        "id": "pm-awas-gramin",
        "name_en": "PM Awas Yojana Gramin (PMAYG)",
        "name_hi": "प्रधानमंत्री आवास योजना ग्रामीण",
        "name_bn": "প্রধানমন্ত্রী আবাস যোজনা গ্রামীণ",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "kind",
        "benefit_summary": "₹1.2 lakh grant for construction of a pucca house in rural areas",
        "benefit_amount": 120000.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 300000.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "unemployed", "woman-homemaker", "artisan"]),
        "bpl_required": 1,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "BPL Certificate", "Land Documents", "Bank Passbook"]),
        "apply_url": "https://pmayg.nic.in",
        "helpline": "1800116446",
        "processing_days": 60,
        "deadline": "Open",
        "rejection_tips": "Must not own a pucca house anywhere in India. Rural residence is mandatory.",
    },
    {
        "id": "pm-ujjwala",
        "name_en": "PM Ujjwala Yojana",
        "name_hi": "प्रधानमंत्री उज्ज्वला योजना",
        "name_bn": "প্রধানমন্ত্রী উজ্জ্বলা যোজনা",
        "ministry": "Ministry of Petroleum and Natural Gas",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "kind",
        "benefit_summary": "Free LPG connection with stove and first cylinder refill",
        "benefit_amount": 0.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "female",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "unemployed", "woman-homemaker", "artisan"]),
        "bpl_required": 1,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "BPL/Ration Card", "Bank Account Passbook"]),
        "apply_url": "https://pmuy.gov.in",
        "helpline": "1906",
        "processing_days": 15,
        "deadline": "Open",
        "rejection_tips": "Applicant must not have an existing LPG connection in the household.",
    },
    {
        "id": "mudra-shishu",
        "name_en": "PM Mudra Loan – Shishu (up to ₹50,000)",
        "name_hi": "प्रधानमंत्री मुद्रा ऋण – शिशु",
        "name_bn": "প্রধানমন্ত্রী মুদ্রা ঋণ – শিশু",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "loan",
        "benefit_summary": "Collateral-free business loan up to ₹50,000 for micro/small businesses",
        "benefit_amount": 50000.0,
        "min_age": 18,
        "max_age": 65,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["self-employed", "street-vendor", "artisan", "farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "PAN Card", "Business Proof / Activity Description"]),
        "apply_url": "https://mudra.org.in",
        "helpline": "1800180111",
        "processing_days": 30,
        "deadline": "Open",
        "rejection_tips": "Business should be non-farm. Avoid agricultural loans under this scheme.",
    },
    {
        "id": "mudra-kishore",
        "name_en": "PM Mudra Loan – Kishore (₹50K–₹5 Lakh)",
        "name_hi": "प्रधानमंत्री मुद्रा ऋण – किशोर",
        "name_bn": "প্রধানমন্ত্রী মুদ্রা ঋণ – কিশোর",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "loan",
        "benefit_summary": "Business loan ₹50,001–₹5 lakh for existing businesses (2+ years)",
        "benefit_amount": 500000.0,
        "min_age": 18,
        "max_age": 65,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["self-employed", "artisan"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "PAN Card", "2-Year Bank Statement", "ITR"]),
        "apply_url": "https://mudra.org.in",
        "helpline": "1800180111",
        "processing_days": 45,
        "deadline": "Open",
        "rejection_tips": "Business must be at least 2 years old with proof. Prepare bank statements properly.",
    },
    {
        "id": "pm-svanidhi",
        "name_en": "PM SVANidhi (Street Vendor Loan)",
        "name_hi": "पीएम स्वनिधि – स्ट्रीट वेंडर ऋण",
        "name_bn": "পিএম স্বনিধি – পথ বিক্রেতা ঋণ",
        "ministry": "Ministry of Housing and Urban Affairs",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "loan",
        "benefit_summary": "Working capital loan ₹10,000–₹50,000 for street vendors with digital credit history",
        "benefit_amount": 10000.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["street-vendor"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Vending Certificate / Letter of Recommendation", "Bank Account"]),
        "apply_url": "https://pmsvanidhi.mohua.gov.in",
        "helpline": "1800111979",
        "processing_days": 30,
        "deadline": "Open",
        "rejection_tips": "Obtain vending certificate from Urban Local Body (ULB) before applying.",
    },
    {
        "id": "sukanya-samridhi",
        "name_en": "Sukanya Samridhi Yojana",
        "name_hi": "सुकन्या समृद्धि योजना",
        "name_bn": "সুকন্যা সমৃদ্ধি যোজনা",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "scholarship",
        "benefit_summary": "High-interest (8.2% p.a.) savings account for girl child's education & marriage",
        "benefit_amount": 0.0,
        "min_age": 0,
        "max_age": 10,
        "gender": "female",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["student", "farmer", "salaried", "self-employed", "unemployed", "woman-homemaker"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Birth Certificate of Girl Child", "Aadhar of Parent/Guardian", "Bank Account"]),
        "apply_url": "https://www.nsiindia.gov.in",
        "helpline": "18002666868",
        "processing_days": 7,
        "deadline": "Open",
        "rejection_tips": "Account must be opened before the girl turns 10. Max 2 girls per family.",
    },
    {
        "id": "jan-dhan",
        "name_en": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
        "name_hi": "प्रधानमंत्री जन धन योजना",
        "name_bn": "প্রধানমন্ত্রী জন ধন যোজনা",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "insurance",
        "benefit_summary": "Zero-balance bank account + ₹2 lakh accident insurance + RuPay debit card",
        "benefit_amount": 200000.0,
        "min_age": 10,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "student", "unemployed", "street-vendor", "artisan", "woman-homemaker", "salaried", "self-employed"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Any Address Proof"]),
        "apply_url": "https://pmjdy.gov.in",
        "helpline": "1800110001",
        "processing_days": 1,
        "deadline": "Open",
        "rejection_tips": "Scheme is for unbanked people. If already have a bank account, you may not be eligible.",
    },
    {
        "id": "pmsby",
        "name_en": "PMSBY – Pradhan Mantri Suraksha Bima Yojana",
        "name_hi": "प्रधानमंत्री सुरक्षा बीमा योजना",
        "name_bn": "প্রধানমন্ত্রী সুরক্ষা বীমা যোজনা",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "insurance",
        "benefit_summary": "₹2 lakh accident death cover + ₹1 lakh partial disability at just ₹20/year premium",
        "benefit_amount": 200000.0,
        "min_age": 18,
        "max_age": 70,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "student", "unemployed", "street-vendor", "artisan", "woman-homemaker", "salaried", "self-employed"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Bank Account with Auto-Debit Consent"]),
        "apply_url": "https://jansuraksha.gov.in",
        "helpline": "1800180111",
        "processing_days": 1,
        "deadline": "Annual renewal by 31 May",
        "rejection_tips": "Auto-debit must be set up. Renew every year before 31 May.",
    },
    {
        "id": "pmjjby",
        "name_en": "PMJJBY – Pradhan Mantri Jeevan Jyoti Bima Yojana",
        "name_hi": "प्रधानमंत्री जीवन ज्योति बीमा योजना",
        "name_bn": "প্রধানমন্ত্রী জীবন জ্যোতি বীমা যোজনা",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "insurance",
        "benefit_summary": "₹2 lakh life insurance cover at ₹436/year premium – covers death from any cause",
        "benefit_amount": 200000.0,
        "min_age": 18,
        "max_age": 50,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "student", "unemployed", "street-vendor", "artisan", "woman-homemaker", "salaried", "self-employed"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Bank Account"]),
        "apply_url": "https://jansuraksha.gov.in",
        "helpline": "1800180111",
        "processing_days": 1,
        "deadline": "Annual renewal by 31 May",
        "rejection_tips": "Age must be 18–50 at enrollment. Premium is auto-debited annually.",
    },
    {
        "id": "atal-pension",
        "name_en": "Atal Pension Yojana (APY)",
        "name_hi": "अटल पेंशन योजना",
        "name_bn": "অটল পেনশন যোজনা",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "cash",
        "benefit_summary": "Guaranteed pension ₹1,000–₹5,000/month after age 60 based on contribution",
        "benefit_amount": 60000.0,
        "min_age": 18,
        "max_age": 40,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "student", "unemployed", "street-vendor", "artisan", "woman-homemaker", "self-employed"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Bank Account", "Mobile Number"]),
        "apply_url": "https://npscra.nsdl.co.in",
        "helpline": "1800110708",
        "processing_days": 7,
        "deadline": "Open",
        "rejection_tips": "Must not be an income tax payer. Not applicable for government employees with pension.",
    },
    {
        "id": "pm-fasal-bima",
        "name_en": "PM Fasal Bima Yojana (PMFBY)",
        "name_hi": "प्रधानमंत्री फसल बीमा योजना",
        "name_bn": "প্রধানমন্ত্রী ফসল বীমা যোজনা",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "insurance",
        "benefit_summary": "Crop insurance against natural calamities, pests and diseases at low premium",
        "benefit_amount": 0.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Land Records", "Bank Account", "Crop Sowing Certificate"]),
        "apply_url": "https://pmfby.gov.in",
        "helpline": "1800116515",
        "processing_days": 60,
        "deadline": "Seasonal – before sowing",
        "rejection_tips": "Enroll before sowing season starts. Tenant farmers can also apply with lease agreement.",
    },
    {
        "id": "mgnregs",
        "name_en": "MGNREGS (100-Day Job Guarantee)",
        "name_hi": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी योजना",
        "name_bn": "মহাত্মা গান্ধী জাতীয় গ্রামীণ কর্মসংস্থান গ্যারান্টি প্রকল্প",
        "ministry": "Ministry of Rural Development",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "cash",
        "benefit_summary": "100 days/year guaranteed unskilled work at state minimum wage in rural areas",
        "benefit_amount": 0.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "unemployed", "artisan", "woman-homemaker"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Job Card from Gram Panchayat", "Bank Account"]),
        "apply_url": "https://nrega.nic.in",
        "helpline": "1800111555",
        "processing_days": 15,
        "deadline": "Open",
        "rejection_tips": "Must be a rural household. Apply for Job Card at Gram Panchayat first.",
    },
    {
        "id": "nsp-scholarship",
        "name_en": "National Scholarship Portal (NSP)",
        "name_hi": "राष्ट्रीय छात्रवृत्ति पोर्टल",
        "name_bn": "ন্যাশনাল স্কলারশিপ পোর্টাল",
        "ministry": "Ministry of Electronics and IT",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "scholarship",
        "benefit_summary": "Scholarships ₹1,000–₹25,000/year for SC/ST/OBC/Minority/Disabled students",
        "benefit_amount": 25000.0,
        "min_age": 14,
        "max_age": 30,
        "gender": "any",
        "income_limit": 250000.0,
        "caste_list": json.dumps(["SC", "ST", "OBC"]),
        "occupation_list": json.dumps(["student"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": "Class 10",
        "documents": json.dumps(["Aadhar Card", "Income Certificate", "Caste Certificate", "Mark Sheet", "Bank Passbook"]),
        "apply_url": "https://scholarships.gov.in",
        "helpline": "0120-6619540",
        "processing_days": 90,
        "deadline": "October–November annually",
        "rejection_tips": "Apply before deadline. Ensure income certificate is in parent's name. OBC NCL required.",
    },
    {
        "id": "pm-vishwakarma",
        "name_en": "PM Vishwakarma Yojana",
        "name_hi": "प्रधानमंत्री विश्वकर्मा योजना",
        "name_bn": "প্রধানমন্ত্রী বিশ্বকর্মা যোজনা",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "kind",
        "benefit_summary": "Free skill training + ₹15,000 toolkit grant + loan up to ₹3 lakh for artisans in 18 trades",
        "benefit_amount": 15000.0,
        "min_age": 18,
        "max_age": 60,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["artisan"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Caste Certificate (if applicable)", "Proof of Trade"]),
        "apply_url": "https://pmvishwakarma.gov.in",
        "helpline": "17923",
        "processing_days": 30,
        "deadline": "Open",
        "rejection_tips": "Eligible trades: carpenter, weaver, blacksmith, potter, tailor, etc. Self-employment in the trade is required.",
    },
    {
        "id": "pmegp",
        "name_en": "PMEGP – PM Employment Generation Programme",
        "name_hi": "प्रधानमंत्री रोजगार सृजन कार्यक्रम",
        "name_bn": "প্রধানমন্ত্রী কর্মসংস্থান সৃষ্টি কর্মসূচি",
        "ministry": "Ministry of MSME",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "loan",
        "benefit_summary": "15–35% subsidy on project cost up to ₹50 lakh for new manufacturing/service businesses",
        "benefit_amount": 1750000.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["unemployed", "self-employed", "artisan"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": "Class 8",
        "documents": json.dumps(["Aadhar Card", "Education Certificate (8th pass)", "Project Report", "Caste Certificate (if applicable)"]),
        "apply_url": "https://www.kviconline.gov.in",
        "helpline": "1800110001",
        "processing_days": 90,
        "deadline": "Open",
        "rejection_tips": "Only for NEW businesses. Prepare a detailed project report. Apply at KVIC/DIC office.",
    },
    {
        "id": "standup-india",
        "name_en": "Stand Up India Scheme",
        "name_hi": "स्टैंड अप इंडिया योजना",
        "name_bn": "স্ট্যান্ড আপ ইন্ডিয়া প্রকল্প",
        "ministry": "Ministry of Finance",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "loan",
        "benefit_summary": "Bank loan ₹10 lakh–₹1 crore for SC/ST and women entrepreneurs for greenfield projects",
        "benefit_amount": 10000000.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST"]),
        "occupation_list": json.dumps(["unemployed", "self-employed", "farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "PAN Card", "Caste/Gender Certificate", "Business Plan", "Bank Statement"]),
        "apply_url": "https://www.standupmitra.in",
        "helpline": "1800180111",
        "processing_days": 90,
        "deadline": "Open",
        "rejection_tips": "SC/ST or women only. Must be first-time greenfield project. Not for existing businesses.",
    },
    {
        "id": "kisan-credit-card",
        "name_en": "Kisan Credit Card (KCC)",
        "name_hi": "किसान क्रेडिट कार्ड",
        "name_bn": "কিষাণ ক্রেডিট কার্ড",
        "ministry": "Ministry of Agriculture & Farmers Welfare",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "loan",
        "benefit_summary": "Credit up to ₹3 lakh at 4% interest rate for short-term agricultural needs",
        "benefit_amount": 300000.0,
        "min_age": 18,
        "max_age": 75,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Land Records", "Aadhar Card", "2 Passport Photos", "Bank Account"]),
        "apply_url": "https://agricoop.nic.in",
        "helpline": "1551",
        "processing_days": 14,
        "deadline": "Open",
        "rejection_tips": "Land must be in your name or you must be a tenant farmer. Allied activity workers also eligible.",
    },
    {
        "id": "pmss",
        "name_en": "PM Scholarship Scheme (PMSS)",
        "name_hi": "प्रधानमंत्री छात्रवृत्ति योजना",
        "name_bn": "প্রধানমন্ত্রী বৃত্তি প্রকল্প",
        "ministry": "Ministry of Home Affairs",
        "scheme_type": "central",
        "state": "all",
        "benefit_type": "scholarship",
        "benefit_summary": "₹2,500–₹3,000/month scholarship for wards of ex-servicemen in professional courses",
        "benefit_amount": 36000.0,
        "min_age": 18,
        "max_age": 25,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["student"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": "Class 12",
        "documents": json.dumps(["Aadhar Card", "Ex-Serviceman Certificate", "Admission Letter", "Mark Sheets"]),
        "apply_url": "https://ksb.gov.in",
        "helpline": "01126715250",
        "processing_days": 60,
        "deadline": "October annually",
        "rejection_tips": "Must be ward of ex-serviceman/coastguard. Professional courses only (medical, engineering, MBA, etc.).",
    },

   
    {
        "id": "lakshmir-bhandar",
        "name_en": "Lakshmir Bhandar (West Bengal)",
        "name_hi": "लक्ष्मीर भंडार (पश्चिम बंगाल)",
        "name_bn": "লক্ষ্মীর ভাণ্ডার (পশ্চিমবঙ্গ)",
        "ministry": "Government of West Bengal",
        "scheme_type": "state",
        "state": "West Bengal",
        "benefit_type": "cash",
        "benefit_summary": "₹500/month (General) or ₹1,000/month (SC/ST) direct cash transfer to women",
        "benefit_amount": 6000.0,
        "min_age": 25,
        "max_age": 60,
        "gender": "female",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "unemployed", "woman-homemaker", "artisan"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Ration Card", "Bank Account (West Bengal)", "Voter ID"]),
        "apply_url": "https://socialsecurity.wb.gov.in",
        "helpline": "1800120101",
        "processing_days": 60,
        "deadline": "Open – apply at Duare Sarkar camp or BDO office",
        "rejection_tips": "Government employees and income tax payers are NOT eligible. WB residence mandatory.",
    },
    {
        "id": "kanyashree-k2",
        "name_en": "Kanyashree K2 (West Bengal)",
        "name_hi": "कन्याश्री K2 (पश्चिम बंगाल)",
        "name_bn": "কন্যাশ্রী K2 (পশ্চিমবঙ্গ)",
        "ministry": "Government of West Bengal – Women and Child Development",
        "scheme_type": "state",
        "state": "West Bengal",
        "benefit_type": "cash",
        "benefit_summary": "₹25,000 one-time grant to girls aged 18–19 who are unmarried and studying",
        "benefit_amount": 25000.0,
        "min_age": 18,
        "max_age": 19,
        "gender": "female",
        "income_limit": 120000.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["student"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": "Class 10",
        "documents": json.dumps(["Aadhar Card", "Income Certificate", "School/College Certificate", "Unmarried Certificate"]),
        "apply_url": "https://wbkanyashree.gov.in",
        "helpline": "18001028014",
        "processing_days": 60,
        "deadline": "Annual",
        "rejection_tips": "Must be unmarried at 18–19. Studying or in vocational training required. Family income < ₹1.2L.",
    },
    {
        "id": "krishak-bandhu",
        "name_en": "Krishak Bandhu (West Bengal)",
        "name_hi": "कृषक बंधु (पश्चिम बंगाल)",
        "name_bn": "কৃষক বন্ধু (পশ্চিমবঙ্গ)",
        "ministry": "Government of West Bengal – Agriculture Department",
        "scheme_type": "state",
        "state": "West Bengal",
        "benefit_type": "cash",
        "benefit_summary": "₹10,000/year to farmers + ₹2 lakh death benefit (age 18–60)",
        "benefit_amount": 10000.0,
        "min_age": 18,
        "max_age": 60,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Land Records (WB)", "Aadhar Card", "Bank Account"]),
        "apply_url": "https://krishakbandhu.net",
        "helpline": "18001804444",
        "processing_days": 45,
        "deadline": "Open",
        "rejection_tips": "Land must be in WB. Apply at BDO office with land records.",
    },
    {
        "id": "swasthya-sathi",
        "name_en": "Swasthya Sathi (West Bengal)",
        "name_hi": "स्वास्थ्य साथी (पश्चिम बंगाल)",
        "name_bn": "স্বাস্থ্য সাথী (পশ্চিমবঙ্গ)",
        "ministry": "Government of West Bengal – Health Department",
        "scheme_type": "state",
        "state": "West Bengal",
        "benefit_type": "insurance",
        "benefit_summary": "₹5 lakh/year cashless health insurance for entire family at empanelled hospitals",
        "benefit_amount": 500000.0,
        "min_age": 0,
        "max_age": 99,
        "gender": "any",
        "income_limit": 999999999.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["farmer", "student", "unemployed", "street-vendor", "artisan", "woman-homemaker", "salaried", "self-employed"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Ration Card or Voter ID (WB)"]),
        "apply_url": "https://swasthyasathi.gov.in",
        "helpline": "18003455384",
        "processing_days": 30,
        "deadline": "Open",
        "rejection_tips": "Available to all WB residents regardless of income. Apply at nearest health facility or Duare Sarkar.",
    },
    {
        "id": "rupashree",
        "name_en": "Rupashree Prakalpa (West Bengal)",
        "name_hi": "रूपश्री प्रकल्प (पश्चिम बंगाल)",
        "name_bn": "রূপশ্রী প্রকল্প (পশ্চিমবঙ্গ)",
        "ministry": "Government of West Bengal – Women and Child Development",
        "scheme_type": "state",
        "state": "West Bengal",
        "benefit_type": "cash",
        "benefit_summary": "₹25,000 one-time marriage assistance to WB girls for first marriage expenses",
        "benefit_amount": 25000.0,
        "min_age": 18,
        "max_age": 99,
        "gender": "female",
        "income_limit": 150000.0,
        "caste_list": json.dumps(["SC", "ST", "OBC", "General"]),
        "occupation_list": json.dumps(["student", "unemployed", "woman-homemaker", "farmer"]),
        "bpl_required": 0,
        "disability_req": 0,
        "min_education": None,
        "documents": json.dumps(["Aadhar Card", "Income Certificate", "Birth Certificate", "Marriage Registration Documents"]),
        "apply_url": "https://wbrupashree.gov.in",
        "helpline": "18001804444",
        "processing_days": 60,
        "deadline": "Apply before or within 60 days of marriage",
        "rejection_tips": "Only for FIRST marriage. Family income must be < ₹1.5L. WB residence required.",
    },
]